name: TonyDeemer
favicon: null
layout_spectrum: 0.75173
typography_spectrum: 0.79836
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f9fdff'
    - '#b31c23'
    - '#11251c'
    - '#7ba750'
    - '#30a6ce'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
