name: TonyDeemer
favicon: null
layout_spectrum: 0.75173
typography_spectrum: 0.79836
title: 'Demo Reel '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#140a09'
    - '#f3dfe4'
    - '#70312d'
    - '#b59e7e'
    - '#a20013'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
