name: TonyDeemer
favicon: null
layout_spectrum: 1
typography_spectrum: 0.79836
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0d0e10'
    - '#e3e2e8'
    - '#b37b69'
    - '#c6c0ab'
    - '#628756'
  brandStrength: 1
  lightness: 0.9375
  saturation: 0.875
  rhythmicContrast: 0.75
purpose: []
