name: TonyDeemer
favicon: null
layout_spectrum: 0.75518
typography_spectrum: 0.79836
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0d0b0e'
    - '#cebe9c'
    - '#729ccf'
    - '#fcfdf7'
    - '#483c2d'
  brandStrength: 1
  lightness: 1
  saturation: 0.875
  rhythmicContrast: 0.5
purpose: []
