name: TonyDeemer
favicon: null
layout_spectrum: 1
typography_spectrum: 0.7625313
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0d080e'
    - '#d9d3c4'
    - '#aba599'
    - '#885c5c'
    - '#3780bd'
  brandStrength: 1
  lightness: 1
  saturation: 0.875
  rhythmicContrast: 0.5
purpose: []
